# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

#       bash install_OpenKim_models.sh
#       pip install kimpy
#       pip install mpcontribs-client
#       pip install optimade[http_client]
#       pip install kim-query

name: Python application

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install OpenKim and download models
      run:
        sudo apt-get install libkim-api-dev openkim-models
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel numpy scipy ase
        pip install asap3
        pip install mp-api
        pip install sqlitedict
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      env:
        MP_API_KEY: ${{secrets.MP_API_KEY}}
      run: |
        pytest
